### ISSUE TITLE
Broken Change Email and Change Password

### ISSUE THREAD

**Issue by sam2b** [kyleb13/MobileAppsGroup1#98]
Since Kevin's commit #78 to ValidateCredential class, these exceptions happen:

```
NullPointerException: Attempt to invoke virtual method 'int group1.tcss450.uw.edu.messageappgroup1.utils.Strings.getInt(int)' on a null object reference
        at group1.tcss450.uw.edu.messageappgroup1.utils.ValidateCredential.validEmail(ValidateCredential.java:47)
        at group1.tcss450.uw.edu.messageappgroup1.ChangeEmailFragment.onClick(ChangeEmailFragment.java:89)
```

```
NullPointerException: Attempt to invoke virtual method 'int group1.tcss450.uw.edu.messageappgroup1.utils.Strings.getInt(int)' on a null object reference
        at group1.tcss450.uw.edu.messageappgroup1.utils.ValidateCredential.validEmail(ValidateCredential.java:47)
        at group1.tcss450.uw.edu.messageappgroup1.ChangePasswordFragment.onClick(ChangeEmailFragment.java)
```

**Comment by sam2b** [comment]
Fixed in PR #101
